#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""泉州 2019/2020 I 端岗位—技能小规模试点采集框架。

本脚本只处理已经取得的官方/高校/政府渠道岗位候选文件，或在没有输入时
生成待采集的候选表与城市年份面板。它不会联网爬取、不会倒填历史年份、
不会修改 latest experimental CCD base panel。
"""

from __future__ import annotations

import argparse
import json
import shutil
from datetime import datetime
from pathlib import Path
from typing import Any

import pandas as pd


TARGET_CITY = "泉州"
TARGET_YEARS = [2019, 2020]

TECH_TRIGGERS = ["技术", "研发", "工程师", "算法", "开发", "数据"]
INDUSTRIAL_TRIGGERS = ["工程师", "技术", "研发", "自动化", "制造", "设备", "工业"]

DEFAULT_TEMPLATE = Path("data/interim/i_system_upgrade/latest_i_system_upgrade_job_posting_candidates_template.xlsx")
DEFAULT_PANEL_TEMPLATE = Path("data/panel/i_system_upgrade/latest_i_system_upgrade_job_city_year_panel_template.xlsx")
DEFAULT_KEYWORDS = Path("config/i_system_upgrade_keywords.yml")

JOB_COLUMNS = [
    "city",
    "year",
    "source_city",
    "job_title",
    "company_name",
    "posting_date",
    "job_description",
    "skill_text",
    "matched_strong_ai_keywords",
    "matched_ai_tool_keywords",
    "matched_basic_digital_keywords",
    "matched_industrial_digital_keywords",
    "matched_weak_keywords",
    "job_classification",
    "job_ai_score",
    "source_url",
    "source_type",
    "collection_status",
    "reviewer_decision",
    "reviewer_notes",
]

PANEL_COLUMNS = [
    "city",
    "year",
    "total_job_count",
    "ai_job_strong_count",
    "ai_tool_based_job_count",
    "digital_tech_job_count",
    "industrial_digital_job_count",
    "broad_ai_digital_job_count",
    "ai_job_ratio",
    "broad_ai_digital_job_ratio",
    "avg_job_ai_score",
    "data_status",
    "notes",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Prepare Quanzhou 2019/2020 job-skill pilot outputs.")
    parser.add_argument("--source-file", help="Optional official/higher-education/government job candidate CSV/XLSX.")
    parser.add_argument("--run-id", help="Optional run_id override.")
    parser.add_argument("--no-update-latest", action="store_true", help="Do not update latest convenience copies.")
    return parser.parse_args()


def ensure_not_legacy(path: Path) -> None:
    text = path.as_posix()
    blocked = ["archive/legacy_outputs", "outputs/ccd_outputs"]
    if any(part in text for part in blocked):
        raise ValueError(f"禁止使用 legacy 或旧式散落输出作为输入：{text}")


def parse_simple_keyword_yaml(path: Path) -> dict[str, list[str]]:
    """Parse the simple list-only YAML generated by i_system_upgrade_prepare.py.

    This avoids adding a PyYAML dependency for a file that only contains
    top-level keys and dash-prefixed scalar values.
    """
    keywords: dict[str, list[str]] = {}
    current_key: str | None = None
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if line.endswith(":"):
            current_key = line[:-1].strip()
            keywords.setdefault(current_key, [])
            continue
        if line.startswith("- ") and current_key:
            keywords[current_key].append(line[2:].strip().strip('"').strip("'"))
    return keywords


def load_template_columns(path: Path, fallback: list[str]) -> list[str]:
    if not path.exists():
        return fallback
    ensure_not_legacy(path)
    try:
        df = pd.read_excel(path, sheet_name=0, nrows=0)
    except Exception:
        return fallback
    return df.columns.tolist() or fallback


def read_source_file(path: Path) -> pd.DataFrame:
    ensure_not_legacy(path)
    if not path.exists():
        raise FileNotFoundError(f"source file does not exist: {path}")
    suffix = path.suffix.lower()
    if suffix == ".csv":
        return pd.read_csv(path)
    if suffix in {".xlsx", ".xls"}:
        return pd.read_excel(path, sheet_name=0)
    raise ValueError(f"仅支持 CSV/XLSX/XLS 输入：{path}")


def normalize_source_jobs(df: pd.DataFrame) -> pd.DataFrame:
    rename_map = {
        "城市": "city",
        "年份": "year",
        "来源城市": "source_city",
        "岗位名称": "job_title",
        "职位名称": "job_title",
        "企业名称": "company_name",
        "公司名称": "company_name",
        "发布日期": "posting_date",
        "发布时间": "posting_date",
        "岗位描述": "job_description",
        "职位描述": "job_description",
        "技能要求": "skill_text",
        "来源链接": "source_url",
        "来源类型": "source_type",
    }
    normalized = df.rename(columns={col: rename_map.get(col, col) for col in df.columns}).copy()
    for col in JOB_COLUMNS:
        if col not in normalized.columns:
            normalized[col] = pd.NA
    normalized["city"] = normalized["city"].fillna(TARGET_CITY).astype(str).str.strip()
    normalized["source_city"] = normalized["source_city"].fillna(normalized["city"]).astype(str).str.strip()
    normalized["year"] = pd.to_numeric(normalized["year"], errors="coerce").astype("Int64")
    normalized["source_type"] = normalized["source_type"].fillna("official_or_manual_input")
    normalized["collection_status"] = normalized["collection_status"].fillna("candidate_unreviewed")
    return normalized[JOB_COLUMNS]


def matched_keywords(text: str, keywords: list[str]) -> list[str]:
    text_lower = text.lower()
    return [keyword for keyword in keywords if keyword.lower() in text_lower]


def has_any(text: str, terms: list[str]) -> bool:
    return any(term in text for term in terms)


def classify_job(row: pd.Series, keywords: dict[str, list[str]]) -> pd.Series:
    title = "" if pd.isna(row.get("job_title")) else str(row.get("job_title"))
    desc = "" if pd.isna(row.get("job_description")) else str(row.get("job_description"))
    skill = "" if pd.isna(row.get("skill_text")) else str(row.get("skill_text"))
    text = f"{title} {desc} {skill}"

    strong = matched_keywords(text, keywords.get("strong_ai_keywords", []))
    tools = matched_keywords(text, keywords.get("ai_tool_keywords", []))
    basic = matched_keywords(text, keywords.get("basic_digital_keywords", []))
    industrial = matched_keywords(text, keywords.get("industrial_digital_keywords", []))
    weak = matched_keywords(text, keywords.get("weak_keywords", []))

    if len(strong) >= 1:
        classification = "ai_job_strong"
        score = 3.0
    elif len(tools) >= 1 and has_any(text, TECH_TRIGGERS):
        classification = "ai_job_tool_based"
        score = 2.5
    elif len(basic) >= 2 and has_any(text, TECH_TRIGGERS):
        classification = "digital_tech_job"
        score = 1.5
    elif len(industrial) >= 1 and has_any(text, INDUSTRIAL_TRIGGERS):
        classification = "industrial_digital_job"
        score = 1.2
    elif weak and not (strong or tools or basic or industrial):
        classification = "weak_only_review"
        score = 0.2
    else:
        classification = "non_ai_job"
        score = 0.0

    row["matched_strong_ai_keywords"] = "、".join(strong)
    row["matched_ai_tool_keywords"] = "、".join(tools)
    row["matched_basic_digital_keywords"] = "、".join(basic)
    row["matched_industrial_digital_keywords"] = "、".join(industrial)
    row["matched_weak_keywords"] = "、".join(weak)
    row["job_classification"] = classification
    row["job_ai_score"] = score
    return row


def filter_target_scope(df: pd.DataFrame) -> tuple[pd.DataFrame, list[str]]:
    warnings: list[str] = []
    before = len(df)
    scoped = df[(df["city"] == TARGET_CITY) & (df["year"].isin(TARGET_YEARS))].copy()
    dropped = before - len(scoped)
    if dropped:
        warnings.append(f"已排除非{TARGET_CITY}或非2019/2020试点范围记录 {dropped} 条。")
    return scoped, warnings


def build_pending_panel() -> pd.DataFrame:
    rows = []
    for year in TARGET_YEARS:
        rows.append(
            {
                "city": TARGET_CITY,
                "year": year,
                "total_job_count": pd.NA,
                "ai_job_strong_count": pd.NA,
                "ai_tool_based_job_count": pd.NA,
                "digital_tech_job_count": pd.NA,
                "industrial_digital_job_count": pd.NA,
                "broad_ai_digital_job_count": pd.NA,
                "ai_job_ratio": pd.NA,
                "broad_ai_digital_job_ratio": pd.NA,
                "avg_job_ai_score": pd.NA,
                "data_status": "pending_collection_no_source_input",
                "notes": "未输入官方历史岗位候选数据；空值不能解释为岗位数为0。",
            }
        )
    return pd.DataFrame(rows, columns=PANEL_COLUMNS)


def build_panel(jobs: pd.DataFrame, has_source_input: bool) -> pd.DataFrame:
    if not has_source_input:
        return build_pending_panel()

    rows = []
    for year in TARGET_YEARS:
        subset = jobs[(jobs["city"] == TARGET_CITY) & (jobs["year"] == year)]
        total = int(len(subset))
        strong = int((subset["job_classification"] == "ai_job_strong").sum())
        tool = int((subset["job_classification"] == "ai_job_tool_based").sum())
        digital = int((subset["job_classification"] == "digital_tech_job").sum())
        industrial = int((subset["job_classification"] == "industrial_digital_job").sum())
        broad = strong + tool + digital + industrial
        rows.append(
            {
                "city": TARGET_CITY,
                "year": year,
                "total_job_count": total,
                "ai_job_strong_count": strong,
                "ai_tool_based_job_count": tool,
                "digital_tech_job_count": digital,
                "industrial_digital_job_count": industrial,
                "broad_ai_digital_job_count": broad,
                "ai_job_ratio": (strong + tool) / total if total else pd.NA,
                "broad_ai_digital_job_ratio": broad / total if total else pd.NA,
                "avg_job_ai_score": subset["job_ai_score"].mean() if total else pd.NA,
                "data_status": "candidate_unreviewed" if total else "source_checked_no_candidate_records",
                "notes": "候选记录尚需人工复核；不能直接替代 current I_index。",
            }
        )
    return pd.DataFrame(rows, columns=PANEL_COLUMNS)


def write_excel(path: Path, sheets: dict[str, pd.DataFrame]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with pd.ExcelWriter(path, engine="openpyxl") as writer:
        for sheet_name, df in sheets.items():
            df.to_excel(writer, index=False, sheet_name=sheet_name[:31])
            ws = writer.book[sheet_name[:31]]
            ws.freeze_panes = "A2"
            ws.auto_filter.ref = ws.dimensions
            for col_cells in ws.columns:
                max_len = max(len(str(cell.value or "")) for cell in col_cells[:80])
                ws.column_dimensions[col_cells[0].column_letter].width = min(max(max_len + 2, 12), 46)


def main() -> None:
    args = parse_args()
    project_root = Path.cwd()
    run_id = args.run_id or datetime.now().strftime("%Y%m%d_%H%M%S")
    created_at = datetime.now().isoformat(timespec="seconds")

    template_path = project_root / DEFAULT_TEMPLATE
    panel_template_path = project_root / DEFAULT_PANEL_TEMPLATE
    keywords_path = project_root / DEFAULT_KEYWORDS

    for path in [template_path, panel_template_path, keywords_path]:
        ensure_not_legacy(path)
        if not path.exists():
            raise FileNotFoundError(f"缺少必要输入：{path}")

    job_columns = load_template_columns(template_path, JOB_COLUMNS)
    panel_columns = load_template_columns(panel_template_path, PANEL_COLUMNS)
    if job_columns != JOB_COLUMNS:
        job_columns = JOB_COLUMNS
    if panel_columns != PANEL_COLUMNS:
        panel_columns = PANEL_COLUMNS

    keywords = parse_simple_keyword_yaml(keywords_path)

    warnings: list[str] = []
    has_source_input = bool(args.source_file)
    if has_source_input:
        source_path = (project_root / args.source_file).resolve() if not Path(args.source_file).is_absolute() else Path(args.source_file)
        jobs = normalize_source_jobs(read_source_file(source_path))
        jobs, scope_warnings = filter_target_scope(jobs)
        warnings.extend(scope_warnings)
    else:
        source_path = None
        jobs = pd.DataFrame(columns=job_columns)
        warnings.append("未提供官方/高校/政府历史岗位候选输入文件，本轮只生成待采集输出，不生成岗位事实记录。")

    if not jobs.empty:
        jobs = jobs.apply(lambda row: classify_job(row, keywords), axis=1)
        jobs = jobs[job_columns]

    panel = build_panel(jobs, has_source_input=has_source_input)
    panel = panel[panel_columns]

    interim_dir = project_root / "data/interim/i_system_upgrade" / run_id
    panel_dir = project_root / "data/panel/i_system_upgrade" / run_id
    audit_dir = project_root / "data/audit/i_system_upgrade" / run_id
    for directory in [interim_dir, panel_dir, audit_dir]:
        directory.mkdir(parents=True, exist_ok=True)

    job_candidates_path = interim_dir / f"i_system_upgrade_job_posting_candidates_{run_id}.xlsx"
    panel_path = panel_dir / f"i_system_upgrade_job_city_year_panel_{run_id}.xlsx"
    manifest_path = audit_dir / f"i_system_upgrade_collect_manifest_{run_id}.json"

    write_excel(
        job_candidates_path,
        {
            "job_posting_candidates": jobs,
            "run_notes": pd.DataFrame(
                {
                    "item": ["target_city", "target_years", "source_file", "warning"],
                    "value": [
                        TARGET_CITY,
                        "2019,2020",
                        str(source_path) if source_path else "",
                        "；".join(warnings),
                    ],
                }
            ),
        },
    )
    write_excel(panel_path, {"job_city_year_panel": panel})

    output_files = [job_candidates_path, panel_path, manifest_path]
    latest_files: list[Path] = []
    if not args.no_update_latest:
        latest_job = project_root / "data/interim/i_system_upgrade/latest_i_system_upgrade_job_posting_candidates.xlsx"
        latest_panel = project_root / "data/panel/i_system_upgrade/latest_i_system_upgrade_job_city_year_panel.xlsx"
        shutil.copy2(job_candidates_path, latest_job)
        shutil.copy2(panel_path, latest_panel)
        latest_files.extend([latest_job, latest_panel])

    manifest = {
        "run_id": run_id,
        "created_at": created_at,
        "target_city": TARGET_CITY,
        "target_years": TARGET_YEARS,
        "input_template": str(template_path),
        "input_panel_template": str(panel_template_path),
        "keywords_file": str(keywords_path),
        "source_file": str(source_path) if source_path else None,
        "source_file_provided": bool(source_path),
        "job_candidate_count": int(len(jobs)),
        "panel_row_count": int(len(panel)),
        "output_files": [str(path) for path in output_files + latest_files],
        "warnings": warnings,
        "legacy_used_as_input": False,
        "commercial_sources_used_as_primary": False,
        "experimental_ccd_base_panel_modified": False,
        "next_step_recommendation": (
            "先采集并人工复核泉州2019/2020官方历史岗位候选；"
            "复核通过后再生成 I_index_upgraded 对比面板，不建议现在重跑 CCD。"
        ),
    }
    manifest_path.write_text(json.dumps(manifest, indent=2, ensure_ascii=False), encoding="utf-8")

    print(json.dumps(manifest, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
